title:              Foundation-Jekyll 

# Versioning
current_version: 1.1.0

author:
  name:             username
  email:            user@domain.com
  github:           username
  twitter:          username

# Dependencies
markdown:           rdiscount
highlighter:        pygments

# Permalinks
permalink:          pretty

# Server
source:             ./source
destination:        ./static

port:               9002
baseurl:            ""
url:                http://yoururl.com

# exclude this stuff when building the static site
exclude:            ["sass","scss",".gitignore","README.md","config.codekit"]


## CUSTOM VARS

#ga_id:             ##-########-###
site_name:          Foundation-Jekyll 
site_description :  A bare bones Foundation & Jekyll boilerplate to get up and running fast.
site_copyright:     Copyright (c) 2014 @aaronkwhite
site_url:           http://yoururl.com
site_email:         site@domain.com
site_phone:         (555) 555-1234 



# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed